-- ============================================================
-- منظور Vault داخل مشروع Supabase الخاص بـ Mail Sender
-- آمن على جداول Mail Sender: ينشئ Schema مستقلة باسم vault
-- لا يحتوي على DROP TABLE ولا يعدل جداول public الحالية
-- ============================================================

create extension if not exists pgcrypto;
create schema if not exists manzor_vault;

grant usage on schema manzor_vault to anon, authenticated, service_role;

create table if not exists manzor_vault.app_users (
  id text primary key,
  display_name text not null,
  role text not null default 'employee',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists manzor_vault.organizations (
  id text primary key,
  name text not null,
  system_url text,
  official_email text,
  channel text,
  city text,
  manager text,
  phone text,
  domain text,
  relationship_start date,
  financial_commitment boolean not null default false,
  financial_amount numeric not null default 0,
  financial_note text,
  last_update timestamptz default now(),
  last_updated_by text,
  notes text,
  support_fund_status text default 'لم يبدأ',
  support_fund_progress integer default 0 check (support_fund_progress between 0 and 100),
  donors_ehsan_status text default 'لم يبدأ',
  donors_ehsan_progress integer default 0 check (donors_ehsan_progress between 0 and 100),
  other_funds_status text default 'لم يبدأ',
  other_funds_progress integer default 0 check (other_funds_progress between 0 and 100),
  created_at timestamptz not null default now()
);

create table if not exists manzor_vault.organization_sites (
  id uuid primary key default gen_random_uuid(),
  organization_id text not null references manzor_vault.organizations(id) on delete cascade,
  title text not null,
  url text not null,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists idx_vault_sites_org on manzor_vault.organization_sites(organization_id);

create table if not exists manzor_vault.organization_accounts (
  id uuid primary key default gen_random_uuid(),
  organization_id text not null references manzor_vault.organizations(id) on delete cascade,
  provider text not null,
  username text,
  password text,
  url text,
  created_at_text text,
  created_at timestamptz not null default now()
);
create index if not exists idx_vault_accounts_org on manzor_vault.organization_accounts(organization_id);

create table if not exists manzor_vault.organization_files (
  id uuid primary key default gen_random_uuid(),
  organization_id text not null references manzor_vault.organizations(id) on delete cascade,
  title text not null,
  category text not null default 'عام',
  file_path text not null,
  file_type text,
  uploaded_by text,
  created_at timestamptz not null default now()
);
create index if not exists idx_vault_files_org on manzor_vault.organization_files(organization_id);

create table if not exists manzor_vault.activity_log (
  id bigint generated by default as identity primary key,
  organization_id text references manzor_vault.organizations(id) on delete set null,
  user_name text,
  action text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_vault_activity_org on manzor_vault.activity_log(organization_id);

insert into manzor_vault.app_users (id, display_name, role, is_active) values
('1001','أمجاد','admin',true),
('1002','أمين','admin',true),
('1003','طلال','admin',true),
('1004','عماد','employee',true),
('1005','بشير','employee',true),
('1006','منير','employee',true),
('1007','عبد الوهاب','employee',true),
('1008','عهد','employee',true),
('1009','حساب المتدرب','trainee',true)
on conflict (id) do update set
  display_name = excluded.display_name,
  role = excluded.role,
  is_active = excluded.is_active;

-- صلاحيات REST API على Schema والجداول
revoke all on all tables in schema manzor_vault from public;
grant select, insert, update, delete on all tables in schema manzor_vault to anon, authenticated;
grant usage, select on all sequences in schema manzor_vault to anon, authenticated;
grant all on all tables in schema manzor_vault to service_role;
grant all on all sequences in schema manzor_vault to service_role;

alter default privileges in schema manzor_vault
  grant select, insert, update, delete on tables to anon, authenticated;
alter default privileges in schema manzor_vault
  grant usage, select on sequences to anon, authenticated;
alter default privileges in schema manzor_vault
  grant all on tables to service_role;
alter default privileges in schema manzor_vault
  grant all on sequences to service_role;

alter table manzor_vault.app_users enable row level security;
alter table manzor_vault.organizations enable row level security;
alter table manzor_vault.organization_sites enable row level security;
alter table manzor_vault.organization_accounts enable row level security;
alter table manzor_vault.organization_files enable row level security;
alter table manzor_vault.activity_log enable row level security;

-- الدخول الحالي برمز الموظف داخل التطبيق، لذلك تظل السياسات متاحة للمفتاح العام.
-- عند الانتقال إلى Supabase Auth يجب استبدال هذه السياسات بسياسات مستخدمين فعلية.
do $$
declare
  t text;
begin
  foreach t in array array[
    'app_users',
    'organizations',
    'organization_sites',
    'organization_accounts',
    'organization_files',
    'activity_log'
  ]
  loop
    execute format('drop policy if exists vault_app_access on manzor_vault.%I', t);
    execute format(
      'create policy vault_app_access on manzor_vault.%I for all to anon, authenticated using (true) with check (true)',
      t
    );
  end loop;
end $$;

-- Bucket مستقل لملفات Vault
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vault-files',
  'vault-files',
  false,
  52428800,
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/svg+xml',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- أسماء سياسات خاصة بـ Vault حتى لا تتعارض مع Mail Sender
drop policy if exists vault_files_read on storage.objects;
drop policy if exists vault_files_insert on storage.objects;
drop policy if exists vault_files_update on storage.objects;
drop policy if exists vault_files_delete on storage.objects;

create policy vault_files_read
on storage.objects for select
to anon, authenticated
using (bucket_id = 'vault-files');

create policy vault_files_insert
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'vault-files');

create policy vault_files_update
on storage.objects for update
to anon, authenticated
using (bucket_id = 'vault-files')
with check (bucket_id = 'vault-files');

create policy vault_files_delete
on storage.objects for delete
to anon, authenticated
using (bucket_id = 'vault-files');

-- بعد تشغيل الملف:
-- Settings > API > Exposed schemas > أضيفي vault ثم Save
