-- منظور Vault V3
-- غير هدّام: لا يحذف بيانات الجمعيات الحالية

create extension if not exists pgcrypto;

create table if not exists app_users (
  id text primary key,
  display_name text not null,
  role text not null default 'employee',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists organizations (
  id text primary key,
  name text not null,
  system_url text,
  official_email text,
  channel text,
  city text,
  manager text,
  phone text,
  domain text,
  relationship_start date,
  financial_commitment boolean not null default false,
  financial_amount numeric not null default 0,
  financial_note text,
  last_update timestamptz default now(),
  last_updated_by text,
  notes text,
  support_fund_status text default 'لم يبدأ',
  support_fund_progress integer default 0 check (support_fund_progress between 0 and 100),
  donors_ehsan_status text default 'لم يبدأ',
  donors_ehsan_progress integer default 0 check (donors_ehsan_progress between 0 and 100),
  other_funds_status text default 'لم يبدأ',
  other_funds_progress integer default 0 check (other_funds_progress between 0 and 100),
  created_at timestamptz not null default now()
);

alter table organizations add column if not exists support_fund_status text default 'لم يبدأ';
alter table organizations add column if not exists support_fund_progress integer default 0;
alter table organizations add column if not exists donors_ehsan_status text default 'لم يبدأ';
alter table organizations add column if not exists donors_ehsan_progress integer default 0;
alter table organizations add column if not exists other_funds_status text default 'لم يبدأ';
alter table organizations add column if not exists other_funds_progress integer default 0;

create table if not exists organization_sites (
  id uuid primary key default gen_random_uuid(),
  organization_id text not null references organizations(id) on delete cascade,
  title text not null,
  url text not null,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists idx_organization_sites_org on organization_sites(organization_id);

create table if not exists organization_accounts (
  id uuid primary key default gen_random_uuid(),
  organization_id text not null references organizations(id) on delete cascade,
  provider text not null,
  username text,
  password text,
  url text,
  created_at_text text,
  created_at timestamptz not null default now()
);
create index if not exists idx_organization_accounts_org on organization_accounts(organization_id);

create table if not exists organization_files (
  id uuid primary key default gen_random_uuid(),
  organization_id text not null references organizations(id) on delete cascade,
  title text not null,
  category text not null default 'عام',
  file_path text not null,
  file_type text,
  uploaded_by text,
  created_at timestamptz not null default now()
);
create index if not exists idx_organization_files_org on organization_files(organization_id);

create table if not exists activity_log (
  id bigint generated by default as identity primary key,
  organization_id text references organizations(id) on delete set null,
  user_name text,
  action text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_activity_log_org on activity_log(organization_id);

insert into app_users (id,display_name,role,is_active) values
('1001','أمجاد','admin',true),('1002','أمين','admin',true),('1003','طلال','admin',true),
('1004','عماد','employee',true),('1005','بشير','employee',true),('1006','منير','employee',true),
('1007','عبد الوهاب','employee',true),('1008','عهد','employee',true),('1009','حساب المتدرب','trainee',true)
on conflict (id) do update set display_name=excluded.display_name,role=excluded.role,is_active=true;

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('organization-files','organization-files',false,52428800,array[
 'application/pdf','image/jpeg','image/png','image/webp','image/svg+xml',
 'application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document',
 'application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
]) on conflict (id) do update set public=false,file_size_limit=52428800,allowed_mime_types=excluded.allowed_mime_types;

-- النسخة الحالية تستخدم رمز موظف داخل التطبيق ولا تستخدم Supabase Auth بعد.
-- لذلك هذه السياسات تتيح التشغيل بالمفتاح العام. للانتاج الحساس ينصح لاحقا بتحويل الدخول إلى Supabase Auth.
alter table app_users enable row level security;
alter table organizations enable row level security;
alter table organization_sites enable row level security;
alter table organization_accounts enable row level security;
alter table organization_files enable row level security;
alter table activity_log enable row level security;

do $$ declare t text; begin
  foreach t in array array['app_users','organizations','organization_sites','organization_accounts','organization_files','activity_log'] loop
    execute format('drop policy if exists vault_anon_all on %I',t);
    execute format('create policy vault_anon_all on %I for all to anon using (true) with check (true)',t);
  end loop;
end $$;

drop policy if exists vault_storage_read on storage.objects;
drop policy if exists vault_storage_insert on storage.objects;
drop policy if exists vault_storage_update on storage.objects;
drop policy if exists vault_storage_delete on storage.objects;
create policy vault_storage_read on storage.objects for select to anon using (bucket_id='organization-files');
create policy vault_storage_insert on storage.objects for insert to anon with check (bucket_id='organization-files');
create policy vault_storage_update on storage.objects for update to anon using (bucket_id='organization-files') with check (bucket_id='organization-files');
create policy vault_storage_delete on storage.objects for delete to anon using (bucket_id='organization-files');
