import React from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Building2, CheckCircle2, Download, Edit3, ExternalLink, FileText, FolderOpen, Globe2, Image as ImageIcon, KeyRound, LogOut, Menu, Plus, Save, Search, Trash2, Upload, X } from 'lucide-react';
import { deleteAccount, deleteAttachment, deleteOrganization, deleteSite, getAttachmentUrl, loadAccounts, loadAttachments, loadOrganizations, loadSites, loadUsers, saveAccount, saveOrganization, saveOrganizationsBulk, saveSite, uploadAttachment } from './lib/repository';
import type { Account, AppUser, Attachment, Organization, SiteLink } from './types';
import './styles.css';

const fallbackUsers: AppUser[]=[{id:'1001',name:'أمجاد',role:'admin'},{id:'1002',name:'أمين',role:'admin'},{id:'1003',name:'طلال',role:'admin'},{id:'1004',name:'عماد'},{id:'1005',name:'بشير'},{id:'1006',name:'منير'},{id:'1007',name:'عبد الوهاب'},{id:'1008',name:'عهد'},{id:'1009',name:'حساب المتدرب',role:'trainee'}];
const categories=['شعار','هوية','عقد','حوكمة','تقرير','مراسلات','منشور','عام'];
const progressStatuses=['لم يبدأ','قيد التجهيز','تم الرفع','تحت المراجعة','مقبول','مرفوض','مكتمل'];
const emptyOrg=(id:string):Organization=>({id,name:'',financial_commitment:false,financial_amount:0,support_fund_status:'لم يبدأ',support_fund_progress:0,donors_ehsan_status:'لم يبدأ',donors_ehsan_progress:0,other_funds_status:'لم يبدأ',other_funds_progress:0});
const norm=(v:string)=>v.toLowerCase().replace(/[إأآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').trim();
const pct=(v?:number|null)=>Math.max(0,Math.min(100,Number(v||0)));
const openUrl=(u?:string|null)=>u&&window.open(u.startsWith('http')?u:`https://${u}`,'_blank');
function errText(e:unknown){return e instanceof Error?e.message:'حدث خطأ غير معروف'}

function Login({onLogin}:{onLogin:(u:AppUser)=>void}){const[id,setId]=React.useState('');const[users,setUsers]=React.useState(fallbackUsers);const[error,setError]=React.useState('');React.useEffect(()=>{loadUsers().then(setUsers)},[]);function submit(e:React.FormEvent){e.preventDefault();const u=users.find(x=>x.id===id.trim());if(!u)return setError('رقم الدخول غير مسجل');onLogin(u)}return <main className="loginPage"><section className="loginCard"><img src="/manzor-vault-icon.png"/><span>منظور تقني</span><h1>منظور Vault</h1><p>إدارة بيانات الجمعيات والملفات ومسارات التقديم</p><form onSubmit={submit}><input autoFocus inputMode="numeric" value={id} onChange={e=>setId(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="رقم الدخول"/>{error&&<small>{error}</small>}<button>دخول</button></form><footer>جميع الحقوق محفوظة لمنظور التقني</footer></section></main>}
function ProgressCard({title,status,value}:{title:string;status?:string|null;value?:number|null}){return <div className="progressCard"><div><strong>{title}</strong><span>{status||'لم يبدأ'}</span></div><b>{pct(value)}%</b><div className="progressTrack"><i style={{width:`${pct(value)}%`}}/></div></div>}
function completion(org:Organization,accounts:Account[],sites:SiteLink[],files:Attachment[]){const checks=[org.name,org.phone,org.official_email,org.city,org.manager,org.relationship_start,org.notes,accounts.length,sites.length,files.some(f=>f.category==='شعار'),files.some(f=>f.category==='عقد')];return Math.round(checks.filter(Boolean).length/checks.length*100)}

function OrganizationView({org,accounts,sites,files,user,onEdit,onBack,onRefresh,onDeleted}:{org:Organization;accounts:Account[];sites:SiteLink[];files:Attachment[];user:AppUser;onEdit:()=>void;onBack:()=>void;onRefresh:()=>Promise<void>;onDeleted:()=>void}){
 const[opening,setOpening]=React.useState(''); const[busy,setBusy]=React.useState(''); const c=completion(org,accounts,sites,files);
 async function openFile(f:Attachment){try{setOpening(f.id);window.open(await getAttachmentUrl(f.file_path),'_blank')}catch(e){alert(errText(e))}finally{setOpening('')}}
 async function remove(kind:'account'|'site'|'file',row:Account|SiteLink|Attachment){if(!confirm('تأكيد حذف العنصر؟'))return;try{setBusy(row.id);if(kind==='account')await deleteAccount(row as Account,user.name);if(kind==='site')await deleteSite(row as SiteLink,user.name);if(kind==='file')await deleteAttachment(row as Attachment,user.name);await onRefresh()}catch(e){alert(errText(e))}finally{setBusy('')}}
 async function removeOrg(){if(!confirm(`تأكيد حذف ${org.name} وجميع بياناتها؟`))return;try{setBusy('org');await deleteOrganization(org.id,user.name);onDeleted()}catch(e){alert(errText(e))}finally{setBusy('')}}
 return <section><div className="pageActions"><button className="ghost" onClick={onBack}><ArrowRight/> رجوع للجمعيات</button><div><button className="danger" onClick={removeOrg} disabled={busy==='org'}><Trash2/> حذف الجمعية</button><button onClick={onEdit}><Edit3/> تعديل البيانات</button></div></div>
 <div className="orgHero"><div><span>{org.id}</span><h2>{org.name}</h2><p>آخر تحديث بواسطة {org.last_updated_by||'غير محدد'}</p></div><div className="completion" style={{background:`conic-gradient(var(--primary) 0 ${c}%,#e9edf5 ${c}% 100%)`}}><b>{c}%</b><small>اكتمال بيانات الجمعية</small></div></div>
 <div className="progressGrid"><ProgressCard title="صندوق دعم الجمعيات" status={org.support_fund_status} value={org.support_fund_progress}/><ProgressCard title="المؤسسات المانحة وإحسان" status={org.donors_ehsan_status} value={org.donors_ehsan_progress}/><ProgressCard title="الصناديق الأخرى" status={org.other_funds_status} value={org.other_funds_progress}/></div>
 <div className="detailGrid"><article><h3><Building2/> بيانات الجمعية</h3><dl><dt>رقم التواصل</dt><dd>{org.phone||'—'}</dd><dt>البريد الرسمي</dt><dd>{org.official_email||'—'}</dd><dt>المدينة</dt><dd>{org.city||'—'}</dd><dt>رئيس المجلس</dt><dd>{org.manager||'—'}</dd><dt>الموقع الإلكتروني</dt><dd>{org.domain?<button className="textLink" onClick={()=>openUrl(org.domain)}>{org.domain}</button>:'—'}</dd><dt>تاريخ بداية الاشتراك</dt><dd>{org.relationship_start||'—'}</dd><dt>الالتزام المالي</dt><dd>{org.financial_commitment?`${org.financial_amount||0} ريال`:'لا يوجد'}</dd><dt>الملاحظات المالية</dt><dd>{org.financial_note||'—'}</dd></dl></article>
 <article><h3><Globe2/> المواقع والروابط</h3>{sites.length?sites.map(s=><div className="dataRow" key={s.id}><button className="rowMain" onClick={()=>openUrl(s.url)}><span>{s.title}<small>{s.url}</small></span><ExternalLink/></button><button className="iconDanger" onClick={()=>remove('site',s)} disabled={busy===s.id}><Trash2/></button></div>):<p className="empty">لا توجد روابط</p>}</article>
 <article><h3><KeyRound/> الحسابات</h3>{accounts.length?accounts.map(a=><div className="account" key={a.id}><strong>{a.provider}</strong><span>{a.username||'—'}</span><code>{a.password||'—'}</code>{a.url&&<button onClick={()=>openUrl(a.url)}>فتح</button>}<button className="iconDanger" onClick={()=>remove('account',a)} disabled={busy===a.id}><Trash2/></button></div>):<p className="empty">لا توجد حسابات</p>}</article>
 <article className="wide"><h3><FolderOpen/> المرفقات</h3><div className="fileGrid">{files.length?files.map(f=><div className="fileItem" key={f.id}><button className="fileOpen" onClick={()=>openFile(f)}><FileText/><span>{f.title}<small>{f.category}</small></span><b>{opening===f.id?'جاري الفتح':'تحميل'}</b></button><button className="iconDanger" onClick={()=>remove('file',f)} disabled={busy===f.id}><Trash2/></button></div>):<p className="empty">لا توجد مرفقات</p>}</div></article>
 <article className="wide"><h3>الملاحظات</h3><p className="notes">{org.notes||'لا توجد ملاحظات'}</p></article></div></section>}

type DraftFile={file:File;category:string};
function EntryPage({initial,currentUser,onCancel,onDone}:{initial:Organization;currentUser:AppUser;onCancel:()=>void;onDone:(o:Organization)=>void}){
 const[form,setForm]=React.useState<Organization>({...initial});const[sites,setSites]=React.useState<SiteLink[]>([]);const[accounts,setAccounts]=React.useState<Account[]>([]);const[files,setFiles]=React.useState<DraftFile[]>([]);const[site,setSite]=React.useState({title:'',url:'',note:''});const[account,setAccount]=React.useState({provider:'',username:'',password:'',url:''});const[category,setCategory]=React.useState('عام');const[saving,setSaving]=React.useState(false);const[done,setDone]=React.useState(false);const[loading,setLoading]=React.useState(Boolean(initial.name));
 React.useEffect(()=>{if(!initial.name){setLoading(false);return}Promise.all([loadSites(initial.id),loadAccounts(initial.id)]).then(([s,a])=>{setSites(s);setAccounts(a)}).catch(e=>alert(errText(e))).finally(()=>setLoading(false))},[initial.id,initial.name]);
 const set=(k:keyof Organization,v:any)=>setForm(p=>({...p,[k]:v}));
 async function saveAll(){if(!form.name.trim())return alert('يرجى إدخال اسم الجمعية');setSaving(true);try{const saved=await saveOrganization(form,currentUser.name);for(const s of sites)await saveSite({...s,organization_id:form.id},currentUser.name);for(const a of accounts)await saveAccount({...a,organization_id:form.id},currentUser.name);for(const f of files)await uploadAttachment(form.id,f.file,f.category,currentUser.name);setDone(true);setTimeout(()=>onDone(saved),650)}catch(e){alert(errText(e))}finally{setSaving(false)}}
 function addSite(){if(!site.title||!site.url)return;setSites(p=>[...p,{id:crypto.randomUUID(),organization_id:form.id,...site}]);setSite({title:'',url:'',note:''})}
 function addAccount(){if(!account.provider)return;setAccounts(p=>[...p,{id:crypto.randomUUID(),organization_id:form.id,...account}]);setAccount({provider:'',username:'',password:'',url:''})}
 function addFiles(fileList:FileList|null,fileCategory:string){const chosen=Array.from(fileList||[]).map(file=>({file,category:fileCategory}));setFiles(p=>[...p,...chosen])}
 if(loading)return <div className="welcome"><p>جاري تحميل بيانات الجمعية</p></div>;
 return <section>{done&&<div className="successToast"><CheckCircle2/> تم تحديث بيانات الجمعية بنجاح</div>}<div className="pageActions"><button className="ghost" onClick={onCancel}><ArrowRight/> رجوع</button><button onClick={saveAll} disabled={saving}><Save/> {saving?'جاري الحفظ':'حفظ كل البيانات'}</button></div><div className="entryTitle"><div><span>{form.id}</span><h2>{initial.name?'تحديث الجمعية':'إضافة جمعية جديدة'}</h2></div></div>
 <div className="formSections"><article><h3>البيانات الأساسية</h3><div className="fields"><label>اسم الجمعية<input value={form.name||''} onChange={e=>set('name',e.target.value)}/></label><label>رقم التواصل<input value={form.phone||''} onChange={e=>set('phone',e.target.value)}/></label><label>البريد الرسمي<input value={form.official_email||''} onChange={e=>set('official_email',e.target.value)}/></label><label>المدينة<input value={form.city||''} onChange={e=>set('city',e.target.value)}/></label><label>رئيس المجلس<input value={form.manager||''} onChange={e=>set('manager',e.target.value)}/></label><label>الموقع الإلكتروني<input value={form.domain||''} onChange={e=>set('domain',e.target.value)}/></label><label>تاريخ بداية الاشتراك<input type="date" value={form.relationship_start||''} onChange={e=>set('relationship_start',e.target.value)}/></label><label>الالتزام المالي<select value={form.financial_commitment?'yes':'no'} onChange={e=>set('financial_commitment',e.target.value==='yes')}><option value="no">لا يوجد</option><option value="yes">يوجد</option></select></label><label>قيمة الالتزام<input type="number" value={form.financial_amount||''} onChange={e=>set('financial_amount',Number(e.target.value))}/></label><label>شعار الجمعية<span className="fileInput"><ImageIcon/> رفع صورة الشعار<input type="file" accept="image/*" onChange={e=>{addFiles(e.target.files,'شعار');e.target.value=''}}/></span></label></div><label>ملاحظات مالية<textarea value={form.financial_note||''} onChange={e=>set('financial_note',e.target.value)}/></label><label>ملاحظات عامة<textarea value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></label></article>
 <article><h3>مسارات التقدم</h3>{[['support_fund','صندوق دعم الجمعيات'],['donors_ehsan','المؤسسات المانحة وإحسان'],['other_funds','الصناديق الأخرى']].map(([k,t])=><div className="trackFields" key={k}><strong>{t}</strong><select value={(form as any)[`${k}_status`]||'لم يبدأ'} onChange={e=>set(`${k}_status` as keyof Organization,e.target.value)}>{progressStatuses.map(status=><option key={status}>{status}</option>)}</select><input type="range" min="0" max="100" value={(form as any)[`${k}_progress`]||0} onChange={e=>set(`${k}_progress` as keyof Organization,Number(e.target.value))}/><b>{(form as any)[`${k}_progress`]||0}%</b></div>)}</article>
 <article><h3>الروابط</h3><div className="inlineFields"><input placeholder="اسم الرابط" value={site.title} onChange={e=>setSite({...site,title:e.target.value})}/><input placeholder="الرابط" value={site.url} onChange={e=>setSite({...site,url:e.target.value})}/><button onClick={addSite}><Plus/></button></div>{sites.map((s,i)=><div className="editableRow" key={s.id}><input value={s.title} onChange={e=>setSites(p=>p.map((x,n)=>n===i?{...x,title:e.target.value}:x))}/><input value={s.url} onChange={e=>setSites(p=>p.map((x,n)=>n===i?{...x,url:e.target.value}:x))}/><button onClick={()=>setSites(p=>p.filter((_,n)=>n!==i))}><X/></button></div>)}</article>
 <article><h3>الحسابات</h3><div className="fields"><input placeholder="اسم النظام أو المؤسسة" value={account.provider} onChange={e=>setAccount({...account,provider:e.target.value})}/><input placeholder="اسم المستخدم" value={account.username} onChange={e=>setAccount({...account,username:e.target.value})}/><input placeholder="كلمة المرور" value={account.password} onChange={e=>setAccount({...account,password:e.target.value})}/><input placeholder="رابط الدخول" value={account.url} onChange={e=>setAccount({...account,url:e.target.value})}/></div><button className="subButton" onClick={addAccount}><Plus/> إضافة الحساب</button>{accounts.map((a,i)=><div className="editableAccount" key={a.id}><input value={a.provider} onChange={e=>setAccounts(p=>p.map((x,n)=>n===i?{...x,provider:e.target.value}:x))}/><input value={a.username||''} onChange={e=>setAccounts(p=>p.map((x,n)=>n===i?{...x,username:e.target.value}:x))}/><input value={a.password||''} onChange={e=>setAccounts(p=>p.map((x,n)=>n===i?{...x,password:e.target.value}:x))}/><input value={a.url||''} onChange={e=>setAccounts(p=>p.map((x,n)=>n===i?{...x,url:e.target.value}:x))}/><button onClick={()=>setAccounts(p=>p.filter((_,n)=>n!==i))}><X/></button></div>)}</article>
 <article className="wide"><h3>المرفقات</h3><div className="uploadRow"><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><label className="upload"><Upload/> اختيار ملفات<input hidden multiple type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx" onChange={e=>{addFiles(e.target.files,category);e.target.value=''}}/></label></div><div className="pendingFiles">{files.map((f,i)=><div key={`${f.file.name}-${i}`}><FileText/><span>{f.file.name}<small>{f.category}</small></span><button onClick={()=>setFiles(p=>p.filter((_,n)=>n!==i))}><X/></button></div>)}</div></article></div></section>}

type ImportedLogo={organizationId:string;file:File};
type ImportResult={organizations:Organization[];logos:ImportedLogo[]};
const templateHeaders=['رقم الجمعية','اسم الجمعية','البريد الرسمي','رقم التواصل','المدينة','رئيس المجلس','الموقع الإلكتروني','تاريخ بداية الاشتراك','التزام مالي نعم أو لا','قيمة الالتزام','ملاحظات مالية','ملاحظات عامة','صورة الشعار','روابط العقود PDF مفصولة بعلامة |','حالة صندوق الدعم','نسبة صندوق الدعم','حالة المؤسسات المانحة وإحسان','نسبة المؤسسات المانحة وإحسان','حالة الصناديق الأخرى','نسبة الصناديق الأخرى'];
function cellText(value:any):string{if(value==null)return '';if(typeof value==='object'){if('text' in value)return String(value.text||'');if('result' in value)return String(value.result||'');if('richText' in value)return value.richText.map(x=>x.text).join('')}return String(value)}
function nextOrganizationId(used:Set<string>){let max=0;for(const id of used){const match=/^ORG-(\d+)$/i.exec(id);if(match)max=Math.max(max,Number(match[1]))}let id='';do{id=`ORG-${String(++max).padStart(3,'0')}`}while(used.has(id));used.add(id);return id}
async function makeTemplate(){if(!(window as any).ExcelJS)throw new Error('تعذر تحميل أداة Excel');const workbook=new (window as any).ExcelJS.Workbook();const sheet=workbook.addWorksheet('الجمعيات',{views:[{rightToLeft:true}]});sheet.addRow(templateHeaders);sheet.addRow(['','جمعية مثال','info@example.org','0500000000','الرياض','اسم رئيس المجلس','https://example.org','2026-01-01','لا','0','','','','','لم يبدأ','0','لم يبدأ','0','لم يبدأ','0']);sheet.getRow(1).font={bold:true};sheet.getRow(1).height=28;sheet.columns=templateHeaders.map((header,index)=>({header,key:`c${index}`,width:index===12?22:index===13?34:20}));sheet.getColumn(13).eachCell(cell=>{cell.alignment={horizontal:'center',vertical:'middle'}});sheet.getRow(2).height=70;sheet.getCell('M2').value='الصق صورة الشعار داخل هذه الخلية';sheet.getCell('N2').value='';const buffer=await workbook.xlsx.writeBuffer();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));a.download='نموذج-استيراد-الجمعيات.xlsx';a.click();URL.revokeObjectURL(a.href)}
async function parseXlsxImport(file:File,existingIds:string[]):Promise<ImportResult>{if(!(window as any).ExcelJS)throw new Error('تعذر تحميل أداة Excel');const workbook=new (window as any).ExcelJS.Workbook();await workbook.xlsx.load(await file.arrayBuffer());const sheet=workbook.worksheets[0];if(!sheet)throw new Error('ملف Excel لا يحتوي على ورقة بيانات');const used=new Set(existingIds);const organizations:Organization[]=[];const rowToOrg=new Map<number,string>();sheet.eachRow((row,rowNumber)=>{if(rowNumber===1)return;const c=templateHeaders.map((_,index)=>cellText(row.getCell(index+1).value).trim());if(!c[1])return;let id=c[0];if(!id)id=nextOrganizationId(used);else if(used.has(id))throw new Error(`رقم الجمعية مكرر: ${id}`);else used.add(id);rowToOrg.set(rowNumber,id);organizations.push({id,name:c[1],official_email:c[2]||null,phone:c[3]||null,city:c[4]||null,manager:c[5]||null,domain:c[6]||null,relationship_start:c[7]||null,financial_commitment:norm(c[8])==='نعم',financial_amount:Number(c[9]||0),financial_note:c[10]||null,notes:c[11]||null,support_fund_status:c[14]||'لم يبدأ',support_fund_progress:pct(Number(c[15]||0)),donors_ehsan_status:c[16]||'لم يبدأ',donors_ehsan_progress:pct(Number(c[17]||0)),other_funds_status:c[18]||'لم يبدأ',other_funds_progress:pct(Number(c[19]||0))})});
 const logos:ImportedLogo[]=[];for(const image of sheet.getImages()){const range:any=image.range;const rowNumber=Number(range?.tl?.nativeRow ?? range?.tl?.row ?? -1)+1;const colNumber=Number(range?.tl?.nativeCol ?? range?.tl?.col ?? -1)+1;if(colNumber!==13)continue;const organizationId=rowToOrg.get(rowNumber);if(!organizationId)continue;const imageData:any=workbook.getImage(image.imageId);if(!imageData)continue;const extension=(imageData.extension||'png').replace('jpeg','jpg');const bytes=imageData.buffer?new Uint8Array(imageData.buffer):imageData.base64?Uint8Array.from(atob(imageData.base64.split(',').pop()||''),char=>char.charCodeAt(0)):null;if(!bytes)continue;logos.push({organizationId,file:new File([bytes],`شعار-${organizationId}.${extension}`,{type:`image/${extension==='jpg'?'jpeg':extension}`})})}return{organizations,logos}}
async function parseLegacyXml(file:File,existingIds:string[]):Promise<ImportResult>{const text=await file.text();const doc=new DOMParser().parseFromString(text,'text/xml');const rows=Array.from(doc.getElementsByTagName('Row')).slice(1);const used=new Set(existingIds);const organizations=rows.map(r=>{const c=Array.from(r.getElementsByTagName('Data')).map(x=>x.textContent||'');let id=c[0];if(!id)id=nextOrganizationId(used);else if(used.has(id))throw new Error(`رقم الجمعية مكرر: ${id}`);else used.add(id);return{id,name:c[1]||'',official_email:c[2],phone:c[3],city:c[4],manager:c[5],domain:c[6],relationship_start:c[7]||null,financial_commitment:norm(c[8]||'')==='نعم',financial_amount:Number(c[9]||0),financial_note:c[10]||null,notes:c[11]||null,support_fund_status:c[14]||'لم يبدأ',support_fund_progress:pct(Number(c[15]||0)),donors_ehsan_status:c[16]||'لم يبدأ',donors_ehsan_progress:pct(Number(c[17]||0)),other_funds_status:c[18]||'لم يبدأ',other_funds_progress:pct(Number(c[19]||0))}}).filter(x=>x.name);return{organizations,logos:[]}}
async function parseImport(file:File,existingIds:string[]):Promise<ImportResult>{return file.name.toLowerCase().endsWith('.xlsx')?parseXlsxImport(file,existingIds):parseLegacyXml(file,existingIds)}

function App(){const[user,setUser]=React.useState<AppUser|null>(null);const[orgs,setOrgs]=React.useState<Organization[]>([]);const[selected,setSelected]=React.useState<Organization|null>(null);const[mode,setMode]=React.useState<'list'|'view'|'entry'>('list');const[query,setQuery]=React.useState('');const[accounts,setAccounts]=React.useState<Account[]>([]);const[sites,setSites]=React.useState<SiteLink[]>([]);const[files,setFiles]=React.useState<Attachment[]>([]);const[menu,setMenu]=React.useState(false);const[error,setError]=React.useState('');
 const reload=React.useCallback(async()=>{try{setError('');setOrgs(await loadOrganizations())}catch(e){setError(errText(e))}},[]);const refreshDetails=React.useCallback(async()=>{if(!selected)return;const[a,s,f]=await Promise.all([loadAccounts(selected.id),loadSites(selected.id),loadAttachments(selected.id)]);setAccounts(a);setSites(s);setFiles(f)},[selected]);React.useEffect(()=>{if(user)reload()},[user,reload]);React.useEffect(()=>{if(selected)refreshDetails().catch(e=>setError(errText(e)))},[selected,refreshDetails]);if(!user)return <Login onLogin={setUser}/>;
 const filtered=orgs.filter(o=>norm([o.id,o.name,o.official_email,o.phone].join(' ')).includes(norm(query)));const nextId=()=>nextOrganizationId(new Set(orgs.map(o=>o.id)));
 async function imported(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{const result=await parseImport(file,orgs.map(o=>o.id));if(!result.organizations.length)return alert('لا توجد جمعيات صالحة للاستيراد');await saveOrganizationsBulk(result.organizations,user!.name);for(const logo of result.logos)await uploadAttachment(logo.organizationId,logo.file,'شعار',user!.name);await reload();alert(`تم استيراد ${result.organizations.length} جمعية${result.logos.length?` ورفع ${result.logos.length} شعار`:''}`)}catch(ex){alert(errText(ex))}e.target.value=''}
 return <main className="appShell"><header><button className="mobileMenu" onClick={()=>setMenu(!menu)}><Menu/></button><img src="/manzor-vault-icon.png"/><div><h1>منظور Vault</h1><p>إدارة الجمعيات ومسارات التقديم</p></div><strong>{user.name}</strong><button className="logout" onClick={()=>setUser(null)}><LogOut/></button></header><div className="shell"><aside className={menu?'open':''}><div className="sideActions"><button onClick={()=>{setSelected(emptyOrg(nextId()));setMode('entry');setMenu(false)}}><Plus/> إضافة جمعية</button><button className="secondary" onClick={makeTemplate}><Download/> تحميل نموذج Excel</button><label className="secondary"><Upload/> رفع الجمعيات<input hidden type="file" accept=".xlsx,.xls,.xml" onChange={imported}/></label></div><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="البحث عن جمعية"/></div><nav>{filtered.map(o=><button className={selected?.id===o.id?'active':''} key={o.id} onClick={()=>{setSelected(o);setMode('view');setMenu(false)}}><span>{o.id}</span><strong>{o.name}</strong></button>)}</nav></aside><section className="workspace">{error&&<div className="errorBanner">{error}</div>}{mode==='list'&&<div className="welcome"><ImageIcon/><h2>إدارة بيانات الجمعيات</h2><p>حدد جمعية من القائمة أو أضف جمعية جديدة</p></div>}{selected&&mode==='view'&&<OrganizationView org={selected} accounts={accounts} sites={sites} files={files} user={user} onEdit={()=>setMode('entry')} onBack={()=>{setMode('list');setSelected(null)}} onRefresh={refreshDetails} onDeleted={async()=>{await reload();setSelected(null);setMode('list')}}/>}{selected&&mode==='entry'&&<EntryPage initial={selected} currentUser={user} onCancel={()=>setMode(selected.name?'view':'list')} onDone={async o=>{await reload();setSelected(o);setMode('view')}}/>}</section></div><footer className="siteFooter">جميع الحقوق محفوظة لمنظور التقني © 2026</footer></main>}
createRoot(document.getElementById('root')!).render(<App/>);
